### ISSUE TITLE
delete_row fails when sugarcube's involved

### ISSUE THREAD

**Issue by wejn** [infinitered/ProMotion#233]
Hi,

I've found out that deleting rows fails when `sugarcube` gem is included.

The trace I'm getting is:

```
2013-07-17 10:03:21.127 Odorik[5765:c07] table_data.rb:25:in `cell:': undefined method `section' for 0:Fixnum (NoMethodError)
        from table.rb:114:in `block in delete_row:'
        from table.rb:111:in `delete_row:'
        from table.rb:227:in `tableView:commitEditingStyle:forRowAtIndexPath:'
2013-07-17 10:03:21.129 Odorik[5765:c07] *** Terminating app due to uncaught exception 'NoMethodError', reason: 'table_data.rb:25:in `cell:': undefined method `section' for 0:Fixnum (NoMethodError)
        from table.rb:114:in `block in delete_row:'
        from table.rb:111:in `delete_row:'
        from table.rb:227:in `tableView:commitEditingStyle:forRowAtIndexPath:'
```

which doesn't make much sense, as there shouldn't be Fixnum passed as index_path to `PM::TableData#cell(params={})`.

Through experimenting I found out that the following line in `delete_row` is the offender:

```
index_paths = Array(index_paths)
```

Changing it to:

```
index_paths = [index_paths] if index_paths.kind_of?(NSIndexPath)
```

resolves the issue for me.

This auto-conversion of `NSIndexPath` to `Array` (through the fact sugarcube supplies `nsindex.to_a`) makes any `Array(index_path)` construct potentially unsafe.

Any take as to how to resolve this the proper way?
(for now I've monkeypatched PM source for myself)

**Comment by rokugou** [comment]
I have same problem with
ProMotion (2.5.0)
sugarcube (3.3.7)

i added a monkey patch for temporary fix
```
module ProMotion
  class TableData
    def cell(params={})
      if params.is_a?(Hash) && params[:index_path]
        if params[:index_path].is_a?(Fixnum)
          params[:index_path] = [0, params[:index_path]].nsindexpath
        end
      end
      params = index_path_to_section_index(params)
      table_section = params[:unfiltered] ? self.data[params[:section]] : self.section(params[:section])
      c = table_section[:cells].at(params[:index].to_i)
      set_data_cell_defaults(c)
    end
  end
end
```

I cannot found 'cell' called from where.

**Comment by jamonholmgren** [comment]
That's weird.
